name: sequential_stacked
description: "A new Flutter project."

# publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Utility
  path: any
  meta: any
  async: any
  convert: any
  equatable: any
  collection: any

  # Logging
  l: ^4.0.2
  stack_trace: ^1.11.1
  sentry_flutter: ^7.18.0

  # State managment
  stacked: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code generation
  build_runner: ^2.4.9
  stacked_generator:

flutter:
  uses-material-design: true
